"""
Personal Profile Builder Agent — Complete Solution
===================================================
Usage:
    python solution.py torvalds
    python solution.py priyasharma --linkedin https://linkedin.com/in/priya-example/

Requirements:
    pip install anthropic PyGithub httpx beautifulsoup4 jinja2 python-dotenv
"""

import os
import re
import json
import argparse
from pathlib import Path
from datetime import datetime, timedelta, timezone

import httpx                                   # ← pip install httpx
from bs4 import BeautifulSoup                  # ← pip install beautifulsoup4
from jinja2 import Environment, FileSystemLoader  # ← pip install jinja2
from dotenv import load_dotenv                 # ← pip install python-dotenv

load_dotenv()

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------
BASE_DIR      = Path(__file__).parent.parent
OUTPUT_DIR    = BASE_DIR / "output"
TEMPLATES_DIR = BASE_DIR / "templates"

ANTHROPIC_API_KEY = os.environ.get("ANTHROPIC_API_KEY", "")
GITHUB_TOKEN      = os.environ.get("GITHUB_TOKEN", "")

OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
TEMPLATES_DIR.mkdir(parents=True, exist_ok=True)

# ---------------------------------------------------------------------------
# Embedded Jinja2 templates (written to disk on first run if missing)
# ---------------------------------------------------------------------------
README_TEMPLATE = """\
<!-- GitHub Profile README — generated by Personal Profile Builder Agent -->

# Hi, I'm {{ profile.name }} 👋

{{ profile.summary }}

## 🛠️ Skills

{% for skill in profile.skills -%}
![{{ skill }}](https://img.shields.io/badge/{{ skill | replace(' ', '_') }}-informational?style=flat)
{% endfor %}

## 🚀 Highlighted Projects

| Project | Description |
|---------|-------------|
{% for proj in profile.projects -%}
| [{{ proj.name }}](https://github.com/{{ profile.github_username }}/{{ proj.name }}) | {{ proj.highlight }} |
{% endfor %}

## 📊 GitHub Stats

- Public repos: **{{ profile.public_repos }}**
- Followers: **{{ profile.followers }}**
- Recent commits (30 days): **{{ profile.recent_commits }}**

---
*Generated by [Personal Profile Builder Agent](https://github.com/{{ profile.github_username }})*
"""

HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ profile.name }}</title>
    <style>
        * { box-sizing: border-box; margin: 0; padding: 0; }
        body { font-family: 'Segoe UI', system-ui, sans-serif; background: #0d1117; color: #c9d1d9; line-height: 1.6; }
        header { background: #161b22; border-bottom: 1px solid #30363d; padding: 2rem; text-align: center; }
        header h1 { font-size: 2rem; color: #f0f6fc; }
        header p { color: #8b949e; margin-top: 0.5rem; }
        header a { color: #58a6ff; }
        main { max-width: 860px; margin: 2rem auto; padding: 0 1.5rem; }
        section { margin-bottom: 2rem; }
        h2 { color: #58a6ff; border-bottom: 1px solid #30363d; padding-bottom: 0.5rem; margin-bottom: 1rem; }
        .skills { display: flex; flex-wrap: wrap; gap: 0.5rem; }
        .skill-tag { background: #1f6feb; color: #f0f6fc; padding: 0.25rem 0.75rem; border-radius: 2rem; font-size: 0.875rem; }
        .project { background: #161b22; border: 1px solid #30363d; border-radius: 6px; padding: 1rem; margin-bottom: 0.75rem; }
        .project a { color: #58a6ff; text-decoration: none; font-weight: 600; }
        footer { text-align: center; padding: 2rem; color: #8b949e; font-size: 0.875rem; }
    </style>
</head>
<body>
    <header>
        <h1>{{ profile.name }}</h1>
        {% if profile.location %}<p>{{ profile.location }}</p>{% endif %}
        <p><a href="{{ profile.github_url }}">GitHub</a></p>
    </header>
    <main>
        <section>
            <h2>About</h2>
            <p>{{ profile.narrative }}</p>
        </section>
        <section>
            <h2>Skills</h2>
            <div class="skills">
                {% for skill in profile.skills %}<span class="skill-tag">{{ skill }}</span>{% endfor %}
            </div>
        </section>
        <section>
            <h2>Projects</h2>
            {% for proj in profile.projects %}
            <div class="project">
                <a href="https://github.com/{{ profile.github_username }}/{{ proj.name }}">{{ proj.name }}</a>
                <p>{{ proj.highlight }}</p>
            </div>
            {% endfor %}
        </section>
    </main>
    <footer>Generated by Personal Profile Builder Agent</footer>
</body>
</html>
"""


def _ensure_templates():
    """Write embedded templates to disk if they do not exist yet."""
    readme_path = TEMPLATES_DIR / "readme.md.j2"
    html_path   = TEMPLATES_DIR / "index.html.j2"
    if not readme_path.exists():
        readme_path.write_text(README_TEMPLATE)
    if not html_path.exists():
        html_path.write_text(HTML_TEMPLATE)


# ---------------------------------------------------------------------------
# GitHub Scraper
# ---------------------------------------------------------------------------
def scrape_github(username: str) -> dict:
    """Fetch public GitHub profile data. Returns a flat dict."""
    try:
        from github import Github, GithubException   # ← pip install PyGithub
    except ImportError:
        raise ImportError("Install PyGithub: pip install PyGithub")

    g    = Github(GITHUB_TOKEN or None)              # ← None = anonymous (60 req/hr)
    user = g.get_user(username)

    # Top repos by star count (skip forks)
    all_repos = list(user.get_repos(type="owner", sort="updated"))
    top_repos = sorted(
        [r for r in all_repos if not r.fork],
        key=lambda r: r.stargazers_count,
        reverse=True,
    )[:5]

    repo_dicts = [
        {
            "name":        repo.name,
            "description": repo.description or "",
            "stars":       repo.stargazers_count,
            "language":    repo.language or "N/A",
            "url":         repo.html_url,
        }
        for repo in top_repos
    ]

    # Aggregate languages (sample first 20 non-fork repos)
    lang_counts: dict = {}
    for repo in [r for r in all_repos if not r.fork][:20]:
        try:
            for lang, byte_count in repo.get_languages().items():
                lang_counts[lang] = lang_counts.get(lang, 0) + byte_count
        except Exception:
            pass
    top_languages = sorted(lang_counts, key=lang_counts.get, reverse=True)[:5]  # type: ignore[arg-type]

    # Recent commits in last 30 days
    since = datetime.now(timezone.utc) - timedelta(days=30)
    recent_commits = 0
    for repo in all_repos[:10]:
        try:
            recent_commits += repo.get_commits(since=since, author=username).totalCount
        except Exception:
            pass

    return {
        "username":       username,
        "name":           user.name or username,
        "bio":            user.bio or "",
        "location":       user.location or "",
        "public_repos":   user.public_repos,
        "followers":      user.followers,
        "top_repos":      repo_dicts,
        "top_languages":  top_languages,
        "recent_commits": recent_commits,
        "github_url":     user.html_url,
    }


# ---------------------------------------------------------------------------
# LinkedIn Scraper
# ---------------------------------------------------------------------------
LINKEDIN_HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/124.0.0.0 Safari/537.36"
    ),
    "Accept-Language": "en-US,en;q=0.9",
}

HEADLINE_SELECTORS = [
    ".top-card-layout__headline",
    ".top-card__subline-item",
    "h2.top-card-layout__headline",
    ".profile-info-subheader",
]
SUMMARY_SELECTORS = [
    ".core-section-container__content p",
    ".summary__text",
    "section.summary p",
    ".show-more-less-html__markup",
]


def scrape_linkedin(url: str) -> dict:
    """Scrape public LinkedIn profile. Never raises — returns fallback on any error."""
    if not url:
        return {"headline": "", "summary": "", "scraped": False}

    try:
        with httpx.Client(timeout=15.0, follow_redirects=True) as client:
            resp = client.get(url, headers=LINKEDIN_HEADERS)

        if resp.status_code != 200:
            return {
                "headline": "", "summary": "", "scraped": False,
                "note": f"HTTP {resp.status_code}",
            }

        soup = BeautifulSoup(resp.text, "html.parser")

        headline = ""
        for sel in HEADLINE_SELECTORS:
            tag = soup.select_one(sel)
            if tag:
                headline = tag.get_text(strip=True)
                break

        summary = ""
        for sel in SUMMARY_SELECTORS:
            tag = soup.select_one(sel)
            if tag:
                summary = tag.get_text(strip=True)
                break

        return {
            "headline": headline,
            "summary":  summary,
            "scraped":  bool(headline or summary),
        }

    except Exception as exc:
        return {"headline": "", "summary": "", "scraped": False, "note": str(exc)}


# ---------------------------------------------------------------------------
# Claude Agent
# ---------------------------------------------------------------------------
SYSTEM_PROMPT = """
You are a professional technical writer and career coach.
Given raw GitHub and LinkedIn data about a software developer,
produce a JSON object with these exact keys:
  - summary:     3-5 sentence professional bio in third person
  - skills:      list of up to 10 skill tag strings (concise, e.g. "Python", "RAG Pipelines")
  - projects:    list of up to 4 objects, each with: name (string), highlight (1 sentence string)
  - narrative:   2-3 sentence career story in first person (for personal website About section)
  - twitter_bio: <=160 characters, first person, punchy, include 1-2 key skills and location if known

Return ONLY valid JSON. No markdown fences. No prose outside the JSON.
""".strip()


def build_profile(github_data: dict, linkedin_data: dict) -> dict:
    """Call Claude to synthesise scraped data into a structured profile dict."""
    import anthropic

    client = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY)

    lines = [
        f"GitHub username: {github_data.get('username', '')}",
        f"Name: {github_data.get('name', '')}",
        f"GitHub bio: {github_data.get('bio', '')}",
        f"Location: {github_data.get('location', '')}",
        f"Public repos: {github_data.get('public_repos', 0)}",
        f"Followers: {github_data.get('followers', 0)}",
        f"Top languages: {', '.join(github_data.get('top_languages', []))}",
        f"Recent commits (30 days): {github_data.get('recent_commits', 0)}",
        "",
        "Top repositories:",
    ]
    for repo in github_data.get("top_repos", []):
        lines.append(
            f"  - {repo['name']} ({repo['language']}, {repo['stars']} stars): "
            f"{repo['description']}"
        )

    if linkedin_data.get("headline"):
        lines += ["", f"LinkedIn headline: {linkedin_data['headline']}"]
    if linkedin_data.get("summary"):
        lines.append(f"LinkedIn summary: {linkedin_data['summary']}")

    context = "\n".join(lines)

    try:
        resp = client.messages.create(
            model="claude-opus-4-5",
            max_tokens=1024,
            system=SYSTEM_PROMPT,
            messages=[{
                "role": "user",
                "content": f"Build a professional profile for this developer:\n\n{context}",
            }],
        )
        raw = resp.content[0].text.strip()

        # Strip accidental markdown code fences
        if raw.startswith("```"):
            parts = raw.split("```")
            raw = parts[1] if len(parts) > 1 else raw  # ← grab content between fences
            if raw.startswith("json"):
                raw = raw[4:]                           # ← remove language hint

        return json.loads(raw)

    except (json.JSONDecodeError, Exception) as exc:
        print(f"  Warning: Claude agent error ({exc}), using fallback profile")
        return {
            "summary":     f"{github_data.get('name', 'A developer')} builds software in "
                           f"{', '.join(github_data.get('top_languages', ['various languages']))}.",
            "skills":      github_data.get("top_languages", []),
            "projects":    [
                {"name": r["name"], "highlight": r["description"]}
                for r in github_data.get("top_repos", [])[:3]
            ],
            "narrative":   "I build open-source software and love clean, maintainable code.",
            "twitter_bio": (
                f"{github_data.get('bio', 'Software developer')} | "
                f"GitHub: @{github_data.get('username', '')}"
            )[:160],
        }


# ---------------------------------------------------------------------------
# Output Generator
# ---------------------------------------------------------------------------
def generate_outputs(github_data: dict, profile: dict) -> dict:
    """Render Jinja2 templates and write output files. Returns {name: path}."""
    _ensure_templates()                             # ← write templates to disk if missing

    # Merge GitHub fields into profile dict for template access
    profile["github_username"] = github_data["username"]
    profile["github_url"]      = github_data["github_url"]
    profile["public_repos"]    = github_data["public_repos"]
    profile["followers"]       = github_data["followers"]
    profile["recent_commits"]  = github_data["recent_commits"]
    profile.setdefault("location", github_data.get("location", ""))
    profile.setdefault("name", github_data.get("name", github_data["username"]))

    env = Environment(
        loader=FileSystemLoader(str(TEMPLATES_DIR)),
        autoescape=False,                           # ← no HTML escaping in markdown templates
    )

    outputs = {}

    # profile_README.md
    readme = env.get_template("readme.md.j2").render(profile=profile)
    readme_path = OUTPUT_DIR / "profile_README.md"
    readme_path.write_text(readme, encoding="utf-8")
    outputs["readme"] = str(readme_path)

    # twitter_bio.txt
    bio = str(profile.get("twitter_bio", ""))[:160]  # ← hard cap at 160 chars
    bio_path = OUTPUT_DIR / "twitter_bio.txt"
    bio_path.write_text(bio, encoding="utf-8")
    outputs["twitter_bio"] = str(bio_path)

    # index.html
    html = env.get_template("index.html.j2").render(profile=profile)
    html_path = OUTPUT_DIR / "index.html"
    html_path.write_text(html, encoding="utf-8")
    outputs["html"] = str(html_path)

    return outputs


# ---------------------------------------------------------------------------
# Orchestrator
# ---------------------------------------------------------------------------
def run(github_username: str, linkedin_url: str = "") -> dict:
    """Full pipeline: scrape -> synthesise -> generate."""
    print(f"Fetching GitHub data for @{github_username} ...")
    github_data = scrape_github(github_username)
    print(f"  Name: {github_data['name']}")
    print(f"  Repos: {github_data['public_repos']} | "
          f"Followers: {github_data['followers']} | "
          f"Languages: {', '.join(github_data['top_languages'])}")

    print("Fetching LinkedIn data ...")
    linkedin_data = scrape_linkedin(linkedin_url)
    if linkedin_data["scraped"]:
        print(f"  Headline: {linkedin_data['headline']}")
    else:
        note = linkedin_data.get("note", "no URL provided")
        print(f"  LinkedIn not available ({note}) — using GitHub data only")

    print("Calling Claude to build profile ...")
    profile = build_profile(github_data, linkedin_data)
    print(f"  Summary: {str(profile.get('summary', ''))[:80]}...")
    print(f"  Skills: {', '.join(profile.get('skills', []))}")

    print("Generating output files ...")
    outputs = generate_outputs(github_data, profile)
    for name, path in outputs.items():
        print(f"  {name}: {path}")

    return outputs


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------
def main():
    parser = argparse.ArgumentParser(
        description="Personal Profile Builder Agent — generate README, bio, and website"
    )
    parser.add_argument("username", help="GitHub username (e.g. torvalds)")
    parser.add_argument(
        "--linkedin", default="",
        help="LinkedIn public profile URL (optional)"
    )
    args = parser.parse_args()
    run(args.username, args.linkedin)
    print("\nDone. Open output/index.html in your browser.")


if __name__ == "__main__":
    main()
